### Get all users
GET http://localhost:8080/mvc/users

### Create new user
POST http://localhost:8080/mvc/users
Content-Type: application/json

{
  "login": "dummy"
}

> {%
    client.assert(response.status === 200);
    client.global.set("userId", response.body.id);
%}

### Get single user
GET http://localhost:8080/mvc/users/{{userId}}

### Delete user
DELETE http://localhost:8080/mvc/users/{{userId}}

> {%
    client.assert(response.status === 200);
    client.global.clear("userId");
%}

### Users SSE
GET http://localhost:8080/sse/users/events

### Upper case SSE - start
POST http://localhost:8080/sse/upper-case?input=a

> {%
    client.assert(response.status === 200);
    client.global.set("uuid", response.body);
%}

### Upper case SSE - results
GET http://localhost:8080/sse/upper-case/{{uuid}}

### No streaming
GET http://localhost:8080/streaming/users

### SSE streaming
GET http://localhost:8080/streaming/users/sse

### NDJSON streaming
GET http://localhost:8080/streaming/users/ndjson

### Upper case echo - WebSocket
WEBSOCKET ws://localhost:8080/ws/upper-case-echo

===
marcin
=== wait-for-server
===
tomasz
=== wait-for-server

### Get all users - WebSocket
WEBSOCKET ws://localhost:8080/ws/users

### Get user by login - WebSocker
WEBSOCKET ws://localhost:8080/ws/user

===
chrosciu
=== wait-for-server
===
octocat
=== wait-for-server

